### ISSUE TITLE
project clean up round 1

### ISSUE THREAD

**Issue by tessam30** [USAID-OHA-SI/glitr#1]
Initial tasks

- [x] functionalize / clean up how color objects are loaded / called (si_colors)

- [x] Font check - is it worth it? (plot_setup)

- [x] Color helpers and captions - separate functions, defaults or other? (plot_setup)

**Comment by achafetz** [comment]
so far, lots of work with **fonts**. 

my thoughts so far is we take advantage of `extrafont`. Load it `onLoad` when you open `glitr`. It will then set a default basefont based on what is available. If Source Sans Pro is there (it can flag if not and provide/point to instructions of how to install), sets that as the basefont. If not, it goes for a default font on Windows that we can decide on. If there is an issue or we don't force `import_fonts()` which I think we should, it can default to sans.
