### ISSUE TITLE
Add function to identify min/max values for dynamic annotations

### ISSUE THREAD

**Issue by baboyma** [USAID-OHA-SI/glitr#38]
Function identifying min/max values to then highlight in plot

**Comment by baboyma** [comment]
This should be moved to `glamr`. Thoughts?

**Comment by achafetz** [comment]
Yeah, this is likely `glamr`. 

User provides the grouping vars as a param to pass into `group_by()` and what column to use for the min/max - maybe the param here is a list of `c(min,max)` as default and users can change this to be just one or the other or median or whatever

**Comment by baboyma** [comment]
Sounds good

**Comment by baboyma** [comment]
Moved to glamr
