### ISSUE TITLE
Error on Vignette build

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/glitr#61]
I'm getting an error with GH Actions doing the CI check. It's not ignoring the vignette despite that being in the yaml file.  I've moved `sf` to the `VignetteBuilder` but that didn't work. You can see quite a few attempts here in this PR, https://github.com/USAID-OHA-SI/glitr/pull/60

I moved `sf` into the `Imports` section, but it shouldn't be a required package (there are also a few other packages that probably don't need to be here either). It didn't help.

I merged the PR into `main` since this was just an issue with the vignette. Thoughts?

**Comment by tessam30** [comment]
- [ ] Check whether or not `sf` needs to be referenced in `si_style_map()`.
